### ISSUE TITLE
why is it so hard to add a jar file to the output?

### ISSUE THREAD

**Issue by exaV** [palantir/gradle-docker#194]
I would like to add the output of the jar task to my image so I can run it inside the container.

What I used to do in my Dockerfile is something like this:
`COPY build/libs/*.jar /app.jar`
I would like to accomplish the same thing with the plugin. Since gradle actually knows the output location of the jar task, I want to use the output path instead of hardcoding "build/libs".

I could not figure out a straightforward way to do this. Is it possible?

**Comment by BenedictRasmussen** [comment]
If I am understanding this correctly, you want to use the jar in your docker build without having to use the copy from `<project-root>/build/libs/your.jar`? If this is correct, this can be accomplished using the `files` config and the associated `copySpec`. If I've misinterpreted, please clarify and I'll try and help out :)

Per the README:
> `files`...The specified files are collected in a Gradle CopySpec which is copied into the Docker build context directory. 

[Gradle CopySpec docs](https://docs.gradle.org/current/javadoc/org/gradle/api/file/CopySpec.html). 
 What this means is that if we include the output from our build using the `files` config, we have added the output to the `copySpec`. If you try to run a `gradle docker` now, you'll get an error similar to the following:

> Task :docker FAILED
COPY failed: stat /var/lib/docker/tmp/docker-builder137608503/support/docker/your.war: no such file or directory

If you try to include your file without using the copySpec to copy your artifacts into the build's context, you'll get the above error because we have not actually done anything with the files yet. We can use the `copySpec` to copy our files into the docker build context. As an example, we create a jar using a jar task. I could include that in my docker image by doing the following:

build.gradle
```
plugins {
    id "java"
    id "com.palantir.docker" version "0.20.1"
}

...

task createJar(type: Jar, dependsOn: classes) {
    // creates jar file
    archiveName = "bras.jar"
    ...
}

docker {
    name "image-name:tag"
    files createJar.outputs
    copySpec.into("build/libs")
}
``` 

Dockerfile
```
COPY build/libs/bras.jar /opt/my/app/installation/
```

**Comment by exaV** [comment]
Thanks a lot for your help. The error was exactly what you described.
After I added `copySpec.into("build/libs)` everything worked like a charm.

It was not clear to me that I needed the copySpec (and in which form) after I read the section about files.

- `files` (optional) an argument list of files to be included in the Docker build context, evaluated per `Project#files`. For example, `files tasks.distTar.outputs` adds the TAR/TGZ file produced by the `distTar` tasks, and `files tasks.distTar.outputs, 'my-file.txt'` adds the archive in addition to file `my-file.txt` from the project root directory. The specified files are collected in a Gradle CopySpec which is copied `into` the Docker build context directory. The underlying CopySpec can be used to copy entire directories into the build context, for example:
````gradle
docker {
    copySpec.from("myDir").into("myDir")
}
````

**Comment by BenedictRasmussen** [comment]
I agree it was a little bit confusing, it took me a bit of time of playing around to figure it out. I'll submit a PR to see if I can clear up the confusion a bit in the `README`.

**Comment by BenedictRasmussen** [comment]
@exaV The `readme` update was merged. Please give it a quick look (I just updated the section describing the `files` config) and if you think the description si more clear now, finish out the issue!

**Comment by pkoenig10** [comment]
Closing now that the README has been updated.
