### ISSUE TITLE
using parameter 'files' does not lead to expected results with directories

### ISSUE THREAD

**Issue by stefan-huettemann** [palantir/gradle-docker#58]
Hi & thank you for this nice plugin.

We have an issue (questions) with configuring `docker` using the `files` parameter:

``` javascript
docker {
    name 'myContainer'
    files 'x'
}
```

where `x` is a directory. 

We would expect that the directory `x` (including all its contents) will get copied to the `build/docker` area.

Instead **only the content** of directory `x` gets copied (not the directory `x` itself).

Using the configuration below leads to the result we would expect from the `files` parameter:

``` javascript
dockerPrepare {
    from('.') {
        include 'x'
    }
}
```

_Questions_:
1. Is this a 'feature' of the `files` parameter?
2. Is the configuration as stated above intended  to be used a such by the design of the plugin?

Thank & Regards
-Stefan

**Comment by markelliot** [comment]
We haven't traditionally used this to add directories, so the behavior isn't intentionally one way or the other.

**Comment by antoineco** [comment]
This behavior is due to the way [`CopySpec.from()`](https://docs.gradle.org/current/javadoc/org/gradle/api/file/CopySpec.html#from%28java.lang.Object[]%29) works, which is also reminded in [Chapter 18. Working With Files](https://docs.gradle.org/current/userguide/working_with_files.html#sec:copying_files):

> When an argument resolves to a directory, everything under that directory (but not the directory itself) is recursively copied into the destination directory.

The default behavior of Docker is to send everything that exists in the same directory as the Dockerfile to the build context (excluding what is defined in the `.dockerignore` file). Sending the content of a directory instead of the directory itself is misleading and breaks the 1:1 compatibility with the CLI, since paths differ in the end.

Thanks for posting this workaround @stefan-huettemann, that definitely helped since I face facing a similar issue.

**Comment by markelliot** [comment]
Thanks -- we'd be happy to take a contribution which decides if an entry is a directory and if so copies the whole directory instead of just the file.

**Comment by stefan-huettemann** [comment]
Hi. Please consider a solution as proposed in https://github.com/palantir/gradle-docker/pull/62.
